apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: playground
  namespace: argocd
spec:
  project: default
  source:
    path: kustomize/overlays/production
    repoURL: https://github.com/oleghalin/argocd-example.git
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: playground