apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: podinfo
  namespace: argocd
spec:
  project: default
  source:
    chart: podinfo
    repoURL: https://stefanprodan.github.io/podinfo
    targetRevision: 6.5.2
    helm:
      releaseName: podinfo
      valuesObject: 
        ingress:
          enabled: true
          hosts:
            - host: app.127.0.0.1.nip.io
              paths:
                - path: /
                  pathType: ImplementationSpecific
  destination:
    server: "https://kubernetes.default.svc"
    namespace: playground