apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-echo
  labels:
    app: http-echo
    component: web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: http-echo
      component: web
  template:
    metadata:
      labels:
        app: http-echo
        component: web
    spec:
      containers:
      - name: http-echo
        image: hashicorp/http-echo
        ports:
        - containerPort: 5678
        resources:
          limits:
            cpu: 1000m
            memory: 1Gi
          requests:
            cpu: 500m
            memory: 512Mi