apiVersion: v1
kind: Service
metadata:
  name: http-echo
  labels:
    app: http-echo
spec:
  type: ClusterIP
  ports:
  - port: 8001
    targetPort: 5678
    protocol: TCP
    name: http
  selector:
    app: http-echo